include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - unawaited_futures
    - avoid_dynamic_calls
    - always_use_package_imports
#   As an Android Studio "sort import on save" option
    - directives_ordering
